### ISSUE TITLE
Create a sharable icon

### ISSUE THREAD

**Issue by baruchiro** [devpage-app/dev.page#12]
I'm presenting at a conference, and I want to give my Twitter handle and my dev.page handle.

I'm thinking about adding this to the "about me" slide:
![image](https://user-images.githubusercontent.com/17686879/190897065-e607ecfa-25a3-454f-b163-0de0ee057ab6.png)

But I can't copy it because it is a styled text, not an SVG.

Do you have a logo or something?

**Comment by liorgrossman** [comment]
Hi Baruch!
Unfortunately, we do not have a proper vector logo.
We use the Ubunutu font, so you might be able to reproduce the above by using the same font.

As a stopgap, I've used Cmd+Plus to zoom in the logo, and took a few screenshots for you on different backgrounds:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/987284/191034932-f761bfea-0443-45ff-94d8-30c22ff3648a.png">
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/987284/191035480-a996f16f-defa-4ec6-9a87-31f0b62e5c4b.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/987284/191035181-a9d80c50-6adf-4d2f-9022-b6e3de9686e4.png">

Hope this helps!

**Comment by baruchiro** [comment]
Thanks!
