### ISSUE TITLE
request for small changes on Editor -> Links -> Link -> Icon List 

### ISSUE THREAD

**Issue by James0x57** [devpage-app/dev.page#5]
Hello!

First: excellent to see openbase's awesome designers get started on something new; the web needs more beautiful design like openbase. Thank you!

Anywho: I have 2 small requests for the Icon dropdown for the links on dev.page editor:

![image](https://user-images.githubusercontent.com/7545075/141194684-3f1492c7-8ac7-43b6-96bd-0ba3436e2870.png)

### 2) **Could you please add the [CodePen.io](https://codepen.io) logo too?**

Thank you! 💜

**Comment by liorgrossman** [comment]
Thanks for your feedback!

We will alphabetize the items for easier lookup.

Can't promise about CodePen - we do want to look at more data before adding additional sites to the list, so we don't end up with too large of a list.

**Comment by liorgrossman** [comment]
We've alphabetized the list of links - thank you for your suggestion.

As for Codepen, at this point we won't add the Codepen icon as there aren't many users with links to Codepen.
