### ISSUE TITLE
Support RTL to the UI 

### ISSUE THREAD

**Issue by AhmedElTabarani** [devpage-app/dev.page#6]
Is it possible to set an option to convert the GUI of the page right to left?

**Comment by liorgrossman** [comment]
Hi Ahmed,
Unfortunately, at this point we do not have support to convert the UI to be right-to-left.
Due to limited resources, it's unlikely that we will add such capability to dev.page in the near time horizon.

**Comment by AhmedElTabarani** [comment]
OK, I'm sorry, but why did you close the issue?
If you are not planning to do it soon and may do it in the future, keep this issue open
Until someone you have, he looks at the issues and sees what he can do
This is the idea of open issues
