### ISSUE TITLE
Add quora.com profile to links

### ISSUE THREAD

**Issue by ochapeau** [devpage-app/dev.page#9]
Hi,
It would be nice to add quora.com in links to have the quora icon instead of the general link icon.
Thanks!

**Comment by liorgrossman** [comment]
Hi there!
Thanks for your suggestion.
I looked at the data for our existing users, and it seems Quora links are extremely rare among the thousands of dev.page profiles.
Therefore, we won't be adding this icon, unfortunately.
P.S. Same applies to other sites/icons people suggested, we keep it only to sites that are popular among our userbase so we do not end up with a list of 100 icons :)
